export default {
  CREATE_RANKING: 'CREATE_RANKING',
  UPDATE_RANKING: 'UPDATE_RANKING',

  CREATE_RANKING_ERROR: 'CREATE_RANKING_ERROR',
  UPDATE_RANKING_ERROR: 'UPDATE_RANKING_ERROR',
  COMMON_ERROR: 'COMMON_ERROR'
};
